version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: "nginx"
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html

  php:
    build: ./docker/php-fpm
    container_name: "laravel"
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  node:
    build: ./docker/node
    container_name: "nuxt"
    tty: true
    volumes: 
      - ./nuxt:/var/www/html/nuxt
    ports:
      - "3000:3000"

volumes:
  mysql-data:
